/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.teamrocket.stockx;

public class Stockx {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Stockx().getGreeting());
    }
}
